version: 0.1

phases:
  prebuild:
    commands:
       - printenv > .env
       - cat .env

  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - dist/index.html
    - dist/favicon.ico
    - dist/css/*
    - dist/js/*
